### PR TITLE
Relative links in tasks output, truncated export cmd in terminal

### LINKED ISSUE #266: [Bug Report]: Monitor fails in vscode after updating to 0.6.0 (VSC-526)
**Describe the bug**
After flashing (successfully), the Monitor terminal appears and prints out a couple of lines showing what appears to be the PATH environment variable. After that, no additional output. Reverting to the 0.5.1 plugin allows it to work again.

**To Reproduce**
Choose the build, flash and monitor option (or just monitor if device is already flashed)
View monitor output terminal in vscode - notice nothing is shown (beyond some environment variable output)

**Expected behavior**
Monitor to show serial output as it did in 0.5.1

**Screenshots**
Screen Shot 2021-01-04 at 10 23 13 AM

**Environment (please complete the following information):**

- OS Name & Version: MacOS X 11.1
- VSCode Version: 1.52.1
- ESP-IDF Version: v4.1
- Python Version: 3.8

**Logs**
{"message":"Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n","stack":"Error: Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n\n\tat /Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:1:7720\n\tat ChildProcess.exithandler (child_process.js:295:7)\n\tat ChildProcess.emit (events.js:223:5)\n\tat maybeClose (internal/child_process.js:1021:16)\n\tat Socket.<anonymous> (internal/child_process.js:430:11)\n\tat Socket.emit (events.js:223:5)\n\tat Pipe.<anonymous> (net.js:664:12)","level":"error","timestamp":"2021-01-04T17:40:48.171Z"}
{"message":"Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n","stack":"Error: Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n\n\tat /Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:1:7720\n\tat ChildProcess.exithandler (child_process.js:295:7)\n\tat ChildProcess.emit (events.js:223:5)\n\tat maybeClose (internal/child_process.js:1021:16)\n\tat Socket.<anonymous> (internal/child_process.js:430:11)\n\tat Socket.emit (events.js:223:5)\n\tat Pipe.<anonymous> (net.js:664:12)","level":"error","timestamp":"2021-01-04T17:45:58.002Z"}
{"message":"Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n","stack":"Error: Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n\n\tat /Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:1:7720\n\tat ChildProcess.exithandler (child_process.js:295:7)\n\tat ChildProcess.emit (events.js:223:5)\n\tat maybeClose (internal/child_process.js:1021:16)\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)","level":"error","timestamp":"2021-01-04T17:51:40.458Z"}
{"message":"ESP-IDF Terminal process ended with exit code 1.","stack":"Error: ESP-IDF Terminal process ended with exit code 1.\n\tat ChildProcess.<anonymous> (/Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:1:258876)\n\tat ChildProcess.emit (events.js:223:5)\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)","level":"error","timestamp":"2021-01-04T17:51:47.609Z"}
{"message":"Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n","stack":"Error: Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n\n\tat /Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:1:7720\n\tat ChildProcess.exithandler (child_process.js:295:7)\n\tat ChildProcess.emit (events.js:223:5)\n\tat maybeClose (internal/child_process.js:1021:16)\n\tat Socket.<anonymous> (internal/child_process.js:430:11)\n\tat Socket.emit (events.js:223:5)\n\tat Pipe.<anonymous> (net.js:664:12)","level":"error","timestamp":"2021-01-04T17:52:35.726Z"}
{"message":"Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n","stack":"Error: Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n\n\tat /Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:1:7720\n\tat ChildProcess.exithandler (child_process.js:295:7)\n\tat ChildProcess.emit (events.js:223:5)\n\tat maybeClose (internal/child_process.js:1021:16)\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)","level":"error","timestamp":"2021-01-04T17:52:54.844Z"}
{"message":"ESP-IDF Terminal process ended with exit code 1.","stack":"Error: ESP-IDF Terminal process ended with exit code 1.\n\tat ChildProcess.<anonymous> (/Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:1:258876)\n\tat ChildProcess.emit (events.js:223:5)\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)","level":"error","timestamp":"2021-01-04T17:53:01.187Z"}
{"message":"Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n","stack":"Error: Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n\n\tat /Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:1:7720\n\tat ChildProcess.exithandler (child_process.js:295:7)\n\tat ChildProcess.emit (events.js:223:5)\n\tat maybeClose (internal/child_process.js:1021:16)\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)","level":"error","timestamp":"2021-01-04T17:53:25.213Z"}
{"message":"Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n","stack":"Error: Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n\n\tat /Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:1:7720\n\tat ChildProcess.exithandler (child_process.js:295:7)\n\tat ChildProcess.emit (events.js:223:5)\n\tat maybeClose (internal/child_process.js:1021:16)\n\tat Socket.<anonymous> (internal/child_process.js:430:11)\n\tat Socket.emit (events.js:223:5)\n\tat Pipe.<anonymous> (net.js:664:12)","level":"error","timestamp":"2021-01-04T17:55:22.215Z"}
{"user":true,"level":"warn","message":"ESP-IDF Monitor was closed.","timestamp":"2021-01-04T17:56:25.385Z"}
{"message":"Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n","stack":"Error: Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n\n\tat /Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:1:7720\n\tat ChildProcess.exithandler (child_process.js:295:7)\n\tat ChildProcess.emit (events.js:223:5)\n\tat maybeClose (internal/child_process.js:1021:16)\n\tat Socket.<anonymous> (internal/child_process.js:430:11)\n\tat Socket.emit (events.js:223:5)\n\tat Pipe.<anonymous> (net.js:664:12)","level":"error","timestamp":"2021-01-04T17:56:25.507Z"}
{"user":true,"level":"warn","message":"ESP-IDF Monitor was closed.","timestamp":"2021-01-04T17:57:25.667Z"}
{"message":"Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n","stack":"Error: Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n\n\tat /Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:1:7720\n\tat ChildProcess.exithandler (child_process.js:295:7)\n\tat ChildProcess.emit (events.js:223:5)\n\tat maybeClose (internal/child_process.js:1021:16)\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)","level":"error","timestamp":"2021-01-04T17:57:25.787Z"}
{"user":true,"level":"warn","message":"ESP-IDF Monitor was closed.","timestamp":"2021-01-04T17:58:36.425Z"}
{"message":"Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n","stack":"Error: Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n\n\tat /Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:1:7720\n\tat ChildProcess.exithandler (child_process.js:295:7)\n\tat ChildProcess.emit (events.js:223:5)\n\tat maybeClose (internal/child_process.js:1021:16)\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)","level":"error","timestamp":"2021-01-04T17:58:36.547Z"}
{"user":true,"message":"Failed to get the eFuse Summary from the chip, please make sure you have selected a valid port","stack":"SyntaxError: /var/folders/m1/ksjmzff53q317v2r9j3j03280000gp/T/espefusejsondump.tmp: Unexpected end of JSON input\n\tat JSON.parse (<anonymous>)\n\tat /Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:8:486068\n\tat /Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:1:42996\n\tat FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)","level":"error","timestamp":"2021-01-04T18:08:28.181Z"}
{"message":"non zero exit code 1\n\nespefuse.py v2.9-dev\nConnecting.....\nTraceback (most recent call last):\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/espefuse.py\", line 1017, in <module>\n    _main()\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/espefuse.py\", line 1010, in _main\n    main()\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/espefuse.py\", line 1004, in main\n    efuses = EspEfuses(esp)\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/espefuse.py\", line 151, in __init__\n    if self[\"BLK3_PART_RESERVE\"].get():\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/espefuse.py\", line 253, in get\n    return self.get_raw()\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/espefuse.py\", line 248, in get_raw\n    value = self.parent.read_efuse(self.data_reg_offs)\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/espefuse.py\", line 195, in read_efuse\n    return self._esp.read_efuse(addr)\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/esptool.py\", line 1362, in read_efuse\n    return self.read_reg(self.EFUSE_REG_BASE + (4 * n))\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/esptool.py\", line 520, in read_reg\n    val, data = self.command(self.ESP_READ_REG, struct.pack('<I', addr))\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/esptool.py\", line 373, in command\n    p = self.read()\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/esptool.py\", line 318, in read\n    return next(self._slip_reader)\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/esptool.py\", line 2190, in slip_reader\n    read_bytes = port.read(1 if waiting == 0 else waiting)\n  File \"/Users/brian/Tools/Espressif/python_env/idf4.1_py3.8_env/lib/python3.8/site-packages/serial/serialposix.py\", line 595, in read\n    raise SerialException(\nserial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)\n","stack":"Error: non zero exit code 1\n\nespefuse.py v2.9-dev\nConnecting.....\nTraceback (most recent call last):\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/espefuse.py\", line 1017, in <module>\n    _main()\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/espefuse.py\", line 1010, in _main\n    main()\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/espefuse.py\", line 1004, in main\n    efuses = EspEfuses(esp)\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/espefuse.py\", line 151, in __init__\n    if self[\"BLK3_PART_RESERVE\"].get():\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/espefuse.py\", line 253, in get\n    return self.get_raw()\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/espefuse.py\", line 248, in get_raw\n    value = self.parent.read_efuse(self.data_reg_offs)\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/espefuse.py\", line 195, in read_efuse\n    return self._esp.read_efuse(addr)\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/esptool.py\", line 1362, in read_efuse\n    return self.read_reg(self.EFUSE_REG_BASE + (4 * n))\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/esptool.py\", line 520, in read_reg\n    val, data = self.command(self.ESP_READ_REG, struct.pack('<I', addr))\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/esptool.py\", line 373, in command\n    p = self.read()\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/esptool.py\", line 318, in read\n    return next(self._slip_reader)\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/esptool.py\", line 2190, in slip_reader\n    read_bytes = port.read(1 if waiting == 0 else waiting)\n  File \"/Users/brian/Tools/Espressif/python_env/idf4.1_py3.8_env/lib/python3.8/site-packages/serial/serialposix.py\", line 595, in read\n    raise SerialException(\nserial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)\n\n\tat ChildProcess.<anonymous> (/Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:1:5233)\n\tat ChildProcess.emit (events.js:223:5)\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)","level":"error","timestamp":"2021-01-04T18:08:57.846Z"}
{"user":true,"message":"Failed to get the eFuse Summary from the chip, please make sure you have selected a valid port","level":"error","timestamp":"2021-01-04T18:08:57.847Z"}
{"user":true,"message":"Failed to get the eFuse Summary from the chip, please make sure you have selected a valid port","stack":"SyntaxError: /var/folders/m1/ksjmzff53q317v2r9j3j03280000gp/T/espefusejsondump.tmp: Unexpected end of JSON input\n\tat JSON.parse (<anonymous>)\n\tat /Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:8:486068\n\tat /Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:1:42996\n\tat FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)","level":"error","timestamp":"2021-01-04T18:09:00.380Z"}
{"message":"non zero exit code 1\n\nespefuse.py v2.9-dev\nConnecting......\nTraceback (most recent call last):\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/espefuse.py\", line 1017, in <module>\n    _main()\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/espefuse.py\", line 1010, in _main\n    main()\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/espefuse.py\", line 1001, in main\n    esp.connect(args.before)\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/esptool.py\", line 505, in connect\n    last_error = self._connect_attempt(mode=mode, esp32r0_delay=False)\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/esptool.py\", line 485, in _connect_attempt\n    self.sync()\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/esptool.py\", line 423, in sync\n    self.command(self.ESP_SYNC, b'\\x07\\x07\\x12\\x20' + 32 * b'\\x55',\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/esptool.py\", line 373, in command\n    p = self.read()\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/esptool.py\", line 318, in read\n    return next(self._slip_reader)\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/esptool.py\", line 2190, in slip_reader\n    read_bytes = port.read(1 if waiting == 0 else waiting)\n  File \"/Users/brian/Tools/Espressif/python_env/idf4.1_py3.8_env/lib/python3.8/site-packages/serial/serialposix.py\", line 595, in read\n    raise SerialException(\nserial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)\n","stack":"Error: non zero exit code 1\n\nespefuse.py v2.9-dev\nConnecting......\nTraceback (most recent call last):\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/espefuse.py\", line 1017, in <module>\n    _main()\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/espefuse.py\", line 1010, in _main\n    main()\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/espefuse.py\", line 1001, in main\n    esp.connect(args.before)\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/esptool.py\", line 505, in connect\n    last_error = self._connect_attempt(mode=mode, esp32r0_delay=False)\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/esptool.py\", line 485, in _connect_attempt\n    self.sync()\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/esptool.py\", line 423, in sync\n    self.command(self.ESP_SYNC, b'\\x07\\x07\\x12\\x20' + 32 * b'\\x55',\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/esptool.py\", line 373, in command\n    p = self.read()\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/esptool.py\", line 318, in read\n    return next(self._slip_reader)\n  File \"/Users/brian/Tools/Espressif/esp-idf/components/esptool_py/esptool/esptool.py\", line 2190, in slip_reader\n    read_bytes = port.read(1 if waiting == 0 else waiting)\n  File \"/Users/brian/Tools/Espressif/python_env/idf4.1_py3.8_env/lib/python3.8/site-packages/serial/serialposix.py\", line 595, in read\n    raise SerialException(\nserial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)\n\n\tat ChildProcess.<anonymous> (/Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:1:5233)\n\tat ChildProcess.emit (events.js:223:5)\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)","level":"error","timestamp":"2021-01-04T18:09:12.669Z"}
{"user":true,"message":"Failed to get the eFuse Summary from the chip, please make sure you have selected a valid port","level":"error","timestamp":"2021-01-04T18:09:12.670Z"}
{"user":true,"message":"Failed to get the eFuse Summary from the chip, please make sure you have selected a valid port","stack":"SyntaxError: /var/folders/m1/ksjmzff53q317v2r9j3j03280000gp/T/espefusejsondump.tmp: Unexpected end of JSON input\n\tat JSON.parse (<anonymous>)\n\tat /Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:8:486068\n\tat /Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:1:42996\n\tat FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)","level":"error","timestamp":"2021-01-04T18:09:15.210Z"}
{"user":true,"message":"Failed to get the eFuse Summary from the chip, please make sure you have selected a valid port","stack":"SyntaxError: /var/folders/m1/ksjmzff53q317v2r9j3j03280000gp/T/espefusejsondump.tmp: Unexpected end of JSON input\n\tat JSON.parse (<anonymous>)\n\tat /Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:8:486068\n\tat /Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:1:42996\n\tat FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)","level":"error","timestamp":"2021-01-04T18:09:44.366Z"}
{"user":true,"message":"Failed to get the eFuse Summary from the chip, please make sure you have selected a valid port","stack":"SyntaxError: /var/folders/m1/ksjmzff53q317v2r9j3j03280000gp/T/espefusejsondump.tmp: Unexpected end of JSON input\n\tat JSON.parse (<anonymous>)\n\tat /Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:8:486068\n\tat /Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:1:42996\n\tat FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)","level":"error","timestamp":"2021-01-04T18:10:06.556Z"}
{"message":"Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n","stack":"Error: Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n\n\tat /Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:1:7720\n\tat ChildProcess.exithandler (child_process.js:295:7)\n\tat ChildProcess.emit (events.js:223:5)\n\tat maybeClose (internal/child_process.js:1021:16)\n\tat Socket.<anonymous> (internal/child_process.js:430:11)\n\tat Socket.emit (events.js:223:5)\n\tat Pipe.<anonymous> (net.js:664:12)","level":"error","timestamp":"2021-01-04T18:10:29.516Z"}
{"user":true,"message":"Failed to get the eFuse Summary from the chip, please make sure you have selected a valid port","stack":"SyntaxError: /var/folders/m1/ksjmzff53q317v2r9j3j03280000gp/T/espefusejsondump.tmp: Unexpected end of JSON input\n\tat JSON.parse (<anonymous>)\n\tat /Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:8:486068\n\tat /Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:1:42996\n\tat FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)","level":"error","timestamp":"2021-01-04T18:10:42.890Z"}
{"user":true,"level":"warn","message":"ESP-IDF Monitor was closed.","timestamp":"2021-01-04T18:15:38.802Z"}
{"message":"Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n","stack":"Error: Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n\n\tat /Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:1:7720\n\tat ChildProcess.exithandler (child_process.js:295:7)\n\tat ChildProcess.emit (events.js:223:5)\n\tat maybeClose (internal/child_process.js:1021:16)\n\tat Socket.<anonymous> (internal/child_process.js:430:11)\n\tat Socket.emit (events.js:223:5)\n\tat Pipe.<anonymous> (net.js:664:12)","level":"error","timestamp":"2021-01-04T18:15:38.930Z"}
{"message":"Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n","stack":"Error: Open On-Chip Debugger  v0.10.0-esp32-20191114 (2019-11-14-14:19)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n\n\tat /Users/brian/.vscode/extensions/espressif.esp-idf-extension-0.6.0/dist/extension.js:1:7720\n\tat ChildProcess.exithandler (child_process.js:295:7)\n\tat ChildProcess.emit (events.js:223:5)\n\tat maybeClose (internal/child_process.js:1021:16)\n\tat Socket.<anonymous> (internal/child_process.js:430:11)\n\tat Socket.emit (events.js:223:5)\n\tat Pipe.<anonymous> (net.js:664:12)","level":"error","timestamp":"2021-01-04T18:22:16.056Z"}

### LINKED ISSUE #329: Closing Monitor before flashing (VSC-579)
If you open the monitor, build your project, then close the monitor,  and try to flash you will get a "ESP-IDF Monitor closed" popup. 
The only way to recover is to close VSC and reopen it to flash again. 

Also, if you already have the monitor open, and try to flash it does close the monitor automatically now, but it cannot then flash. I think you need a bit of a delay from the close to when you actually try to flash.

### LINKED ISSUE #333: [Bug Report]: Project relative paths in terminal not resolved on Ctrl+Click (VSC-581)
**Describe the bug**
Version 1.0.0
Ctrl+Click on a relative path in build output in the terminal window results in a VS Code popup indicating that the file could not be found.
eg. 
Terminal:
```
../main/hello_world.c: In function 'app_main':
../main/hello_world.c:28:5: error: 'qwerty' undeclared (first use in this function); did you mean 'qsort'?
     qwerty;
     ^~~~~~
```
VS Code popup upon Ctrl+Click on any relative path (eg. "../main/hello_world.c:28:5"):
```
../main/hello_world.c:28:5
No matching results
```

Absolute paths work correctly. This only affects relative paths. 

**More info**
This was working in 0.5.1.
git bisect:
7abc85897490e3586fa5329e8a1f4c94680019f2 is the first bad commit

### PR DESCRIPTION
**Pull request by brianignacio5**
Fix #333 

Fix #266 

Fix #329

Use vscode ShellExecution to fix relative paths link in build/flash task outputs. PTAL @boarchuz 

Remove export cmd and use strict env for Monitor terminal and ESP-IDF Terminal . PTAL @resetnow

Fix closing monitor issues when flash is trigger. PTAL @seulater

### CODE REVIEW

**Comment by resetnow** [comment]
@brianignacio5 thank you for the update, I tested this PR and I'm observing the following:

1) after a fresh start, monitor command works 🎉 
2) after a fresh start, build-flash-monitor sequence works
3) unfortunately, if the monitor is running and I'm trying to flash, there will be an error:

image

I think the reason is that the serial resource is not released quickly enough - perhaps the terminal is closed or the process is killed asynchronously?

**Comment by brianignacio5** [comment]
I think is about giving enough time for monitor to be disposed. Will check if we have access to terminal disposed event and exit status, timeout is a tricky thing, otherwise just add a timeout configuration setting for this.

**Comment by resetnow** [comment]
This works better - I haven't been able to find any problems
