### ISSUE TITLE
[Bug Report]: Project relative paths in terminal not resolved on Ctrl+Click (VSC-581)

### ISSUE THREAD

**Issue by boarchuz** [espressif/vscode-esp-idf-extension#333]
**Describe the bug**
Version 1.0.0
Ctrl+Click on a relative path in build output in the terminal window results in a VS Code popup indicating that the file could not be found.
eg. 
Terminal:
```
../main/hello_world.c: In function 'app_main':
../main/hello_world.c:28:5: error: 'qwerty' undeclared (first use in this function); did you mean 'qsort'?
     qwerty;
     ^~~~~~
```
VS Code popup upon Ctrl+Click on any relative path (eg. "../main/hello_world.c:28:5"):
```
../main/hello_world.c:28:5
No matching results
```

Absolute paths work correctly. This only affects relative paths. 

**More info**
This was working in 0.5.1.
git bisect:
7abc85897490e3586fa5329e8a1f4c94680019f2 is the first bad commit

**Comment by brianignacio5** [comment]
Thanks for reporting this @boarchuz . I roll back to `shellExecution` since the original problem is gone. PTAL #337

**Comment by boarchuz** [comment]
Thanks, @brianignacio5 , that's fixed it
